### ISSUE TITLE
sentence_xlncet_config.json 오류

### ISSUE THREAD

**Issue by JngHyun** [BM-K/KoSentenceBERT-SKT#5]
안녕하세요,
작성해 주신 코드 바탕으로 진행중에
No such file or directory: './KoSentenceBERT_SKTBERT/output/training_sts/0_Transformer/sentence_xlnet_config.json'

와 같은 오류가 뜨는데 혹시 sentence_xlnet_config.json 파일은 어떻게 생성되는 건가요?
0_Transformer에 구성되어야 하는 다른 파일들이 있는지 궁금합니다!

**Comment by BM-K** [comment]
0_Transformer 디렉토리엔 result.pt 파일이 위치해 있음 됩니다.
xlnet_config 파일이 있는 것으로 봐선 bert가 아닌 xlnet을 통해 siamese 네트워크를 구성한 것 같은데, bert로 바꿔주셔야 할 것 같습니다.

**Comment by kayla220** [comment]
@BM-K 안녕하세요. 말씀 하신 것과 같이 0_Transformer 디렉토리에 result.pt를 위치시킨 후

> 0_Transformer/result.pt

`python3 training_nli.py`

코드를 실행해 본 결과 아래와 같이 0_Transformer 폴더 안에 sentence_bert_config.json 파일이 필요하다고 뜹니다. 

![화면 캡처 2021-08-05 171733](https://user-images.githubusercontent.com/16193985/128316980-a3d0dd61-575c-48a4-a4b8-043c7d9ac8a0.png)

configuration json 파일은 어디를 참고하여야 할까요?
감사합니다.

**Comment by fenneccat** [comment]
@BM-K 저도 @kayla220 님과 동일하게 No such file or directory: './KoSentenceBERT_SKTBERT/output/training_sts/0_Transformer/sentence_bert_config.json' 이러한 에러가 발생합니다. config file을 어디서 구할 수 있는지 말씀해주시면 감사하겠습니다

**Comment by kayla220** [comment]
@fenneccat 님, 저는 wikidocs에도 적혀있듯이 결국 sentence_transformers, tokenizers, transformers이 세 폴더의 경로가 꼬여서 위와같은 에러가 발생하였었습니다. 
`/opt/conda/lib/python3.7/sentence_transformers` 가 아닌 `/opt/sentence_transformers` 와 같이 폴더를 바꾼뒤 코드내에서 import 할때 `from opt.sentence_transformers import SentenceTransformer` 와 같이 불러오시면 경로가 꼬이지 않아 올바른 method를 불러와 에러가 해결되었습니다!
