### ISSUE TITLE
IndexError: index 16 is out of bounds for dimension 0 with size 16

### ISSUE THREAD

**Issue by bbandft** [BM-K/KoSentenceBERT-SKT#7]
<img width="990" alt="스크린샷 2021-08-02 오전 11 42 44" src="https://user-images.githubusercontent.com/45285083/127797637-bfdacf16-c411-4a0b-a103-030f103570fe.png">

corpus의 길이 570글자 안으로 실행할 때 오류 안 뜨는데 570글자 초과하면 위와 같은 오류 뜹니다.

**Comment by BM-K** [comment]
BERT 자체 max sequence length가 512로 설정되어 있어서 그 이상의 값을 넣으면 안 될 것 같습니다.
- https://arxiv.org/pdf/1905.05583.pdf
    - " The first factor is the preprocessing of long text since the maximum sequence length of BERT is 512. "

**Comment by bbandft** [comment]
> BERT 자체 max sequence length가 512로 설정되어 있어서 그 이상의 값을 넣으면 안 될 것 같습니다.
> 
> * https://arxiv.org/pdf/1905.05583.pdf
>   
>   * " The first factor is the preprocessing of long text since the maximum sequence length of BERT is 512. "

corpus의 문장 16개 안일 때 코드 정상적으로 돌아갑니다. 16개 초과하면 아래와 같은 오류 뜬 것 같습니다.
![IMG_7879](https://user-images.githubusercontent.com/45285083/130556563-4c1a45ba-0d35-4cbe-a8bd-42226bab49a0.JPG)

**Comment by BM-K** [comment]
pre-training 당시 batch size를 16으로 설정하고 학습하였기 때문에,  16개 초과시 에러가 납니다.
이 부분에 대해선 수정이 이뤄진 상태라  다시 clone 하셔서 사용하시면 될 것 같습니다.

**Comment by bbandft** [comment]
빠른 답변해주셔서 감사합니다.

clone하고 나서 16개 문장을 초과할 때 여전히 오류 뜹니다. ㅠ 지난번과 다르게 이렇게 오류 떴습니다. 
![IMG_7882](https://user-images.githubusercontent.com/45285083/130605752-6e2ad5ba-ff82-49c3-9c93-9f0f1c4a4d07.JPG)

**Comment by BM-K** [comment]
다음 repository 사용을 권장합니다.
https://github.com/BM-K/Sentence-Embedding-is-all-you-need
